version: '3'
services:
  api:
    build: ./api
    ports:
      - 5000:5000

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=root
      - PORTGRES_DB=football
    volumes:
      - /home/justin/docker/volumes/postgres:/var/lib/postgresql/data

