"""empty message

Revision ID: 99a69d38100f
Revises: b661d6d7a7cf
Create Date: 2019-07-31 11:26:09.779016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99a69d38100f'
down_revision = 'b661d6d7a7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_players_nonppr',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('proj_points', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_index(op.f('ix_espn_players_nonppr_proj_points'), 'espn_players_nonppr', ['proj_points'], unique=True)
    op.drop_index('ix_espn_players_proj_points', table_name='espn_players')
    op.drop_table('espn_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_players',
    sa.Column('rank', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('proj_points', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rank', name='espn_players_pkey')
    )
    op.create_index('ix_espn_players_proj_points', 'espn_players', ['proj_points'], unique=True)
    op.drop_index(op.f('ix_espn_players_nonppr_proj_points'), table_name='espn_players_nonppr')
    op.drop_table('espn_players_nonppr')
    # ### end Alembic commands ###
