"""empty message

Revision ID: 4755d997d93b
Revises: dde80b80b966
Create Date: 2019-08-02 14:00:22.521370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4755d997d93b'
down_revision = 'dde80b80b966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espn_players_nonppr', sa.Column('picked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espn_players_nonppr', 'picked')
    # ### end Alembic commands ###
